---
version: '3.6'

services:
  ircd:
    image: oragono/oragono
    container_name: ircd
    ports:
      - 6667:6667

  compiledaemon:
    image: klumhru/compiledaemon
    container_name: compiler
    entrypoint: CompileDaemon -build="go build" -directory="/repo" -exclude-dir=".git" -command="/repo/ircbot"
    volumes:
      - ./:/repo
    environment:
      IRC_SERVER: ircd:6667
      IRC_CHANNELS: "#gowon"
      IRC_USER: gowon
      IRC_NICK: gowon
      IRC_TLS_SERVER_NAME: na
      IRC_TENOR_API: "${IRC_TENOR_API}"
      IRC_LASTFM_API: "${IRC_LASTFM_API}"
      IRC_TRAKT_API: "${IRC_TRAKT_API}"
